version: 2

project_name: portal

builds:
  - id: portal
    main: .
    binary: portal
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/leeovery/portal/cmd.version={{.Version}}

archives:
  - id: portal
    formats:
      - tar.gz
    name_template: "portal_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

changelog:
  disable: true

release:
  draft: false
