package cmd

// Consolidated regression guard for Phase 5 of the CLI verb-surface redesign
// (spec §§ "attach — Retired", "Command Surface Summary" (Removed; Hidden),
// "Back-Compat & Deprecation Story", "Bare portal (no subcommand)").
//
// attach and spawn are DELETED OUTRIGHT — not aliased, not deprecated-with-
// warning. This file proves the two verbs are unreachable through every surface
// (child registration, cobra alias, --help / bare-portal help, generated
// completion) AND that every behaviour they used to carry is reachable via
// `open` (the --session pin, the hidden --ack receipt flag, multi-target
// positionals).
//
// SCOPE — asserts ONLY the two verbs' absence + open's reachability. The
// state-namespace hiding, the hooks→hook rename (+ its silent `hooks` cobra
// alias), and the finalized tab-completion candidate surface are Phase 6 and
// are deliberately NOT asserted here.
//
// x/xctl are untouched: the `portal init <shell>` emitted `x` function still
// maps to `portal open` (not attach/spawn). That contract is already covered by
// the init tests — see TestInitZsh / TestInitBash / TestInitFish in
// init_test.go ("outputs x function routing to portal open") — so it is
// referenced here rather than duplicated.
//
// Tests mutate no package-level state and MUST NOT use t.Parallel (cmd-package
// convention — mocks are injected via package-level mutable state elsewhere).

import (
	"bytes"
	"fmt"
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

var retiredVerbs = []string{"attach", "spawn"}

// allCommandsInTree returns c and every descendant command (hidden ones
// included — cobra's Commands() surfaces hidden children, so a back-compat shim
// hidden anywhere in the tree is still caught).
func allCommandsInTree(c *cobra.Command) []*cobra.Command {
	out := []*cobra.Command{c}
	for _, child := range c.Commands() {
		out = append(out, allCommandsInTree(child)...)
	}
	return out
}

// (Command-column parsing of the "Available Commands:" section — matching on
// the leading word so a prose mention could not false-positive — reuses the
// shared availableCommandNames helper in state_test.go.)

// TestRetiredSurface_NoChildNamedAttachOrSpawn asserts rootCmd registers no
// child command named attach or spawn (visible or hidden).
func TestRetiredSurface_NoChildNamedAttachOrSpawn(t *testing.T) {
	for _, c := range rootCmd.Commands() {
		for _, verb := range retiredVerbs {
			if c.Name() == verb {
				t.Errorf("%q must be retired — found a child command named %q on rootCmd", verb, verb)
			}
		}
	}
}

// TestRetiredSurface_NoAliasResolvesToRetiredVerbs asserts that neither verb
// survives as a cobra alias (a silent back-compat shim) on any command in the
// tree, and that resolving the bare token lands on the ROOT with the token
// unmatched — which distinguishes "deleted" from "kept behind a silent alias".
//
// NOTE — the ONLY sanctioned silent cobra alias in this redesign is the Phase-6
// hooks→hook carve-out (`portal hooks …` keeps working because it is auto-
// generated by an external skill). That carve-out is deliberate and targeted;
// it does NOT apply to attach/spawn, which take no alias and no deprecation
// warning. This test is the guard that no such shim exists for the two verbs.
func TestRetiredSurface_NoAliasResolvesToRetiredVerbs(t *testing.T) {
	for _, c := range allCommandsInTree(rootCmd) {
		for _, alias := range c.Aliases {
			for _, verb := range retiredVerbs {
				if alias == verb {
					t.Errorf("command %q carries a back-compat alias %q — attach/spawn must take no alias", c.Name(), verb)
				}
			}
		}
	}

	// cobra's Find returns (*Command, remainingArgs, error). For an unmatched
	// leading token it walks no further and returns the command it stopped on —
	// here rootCmd — with the token still in the remaining args. A silent alias
	// would instead resolve Find to the aliased command, so `found == rootCmd`
	// plus the token surviving in `rest` proves the verb is genuinely gone.
	for _, verb := range retiredVerbs {
		found, rest, _ := rootCmd.Find([]string{verb})
		if found != rootCmd {
			t.Errorf("Find([%q]) resolved to command %q — expected the unmatched-token fall-through to rootCmd (verb is deleted, not aliased)", verb, found.Name())
		}
		if len(rest) != 1 || rest[0] != verb {
			t.Errorf("Find([%q]) consumed the token (rest=%v) — an unmatched retired verb must survive as a remaining arg", verb, rest)
		}
	}
}

// TestRetiredSurface_AbsentFromHelp asserts neither verb appears as a command
// entry in the root help/usage (the same "Available Commands" block bare
// `portal` and `portal --help` print).
func TestRetiredSurface_AbsentFromHelp(t *testing.T) {
	names := availableCommandNames(rootCmd.UsageString())
	if len(names) == 0 {
		t.Fatal("no commands parsed from Available Commands section — parser or usage layout changed")
	}
	for _, verb := range retiredVerbs {
		if names[verb] {
			t.Errorf("retired verb %q listed as an Available Command in help", verb)
		}
	}
}

// TestRetiredSurface_AbsentFromCompletion asserts neither verb is offered as a
// root subcommand in the generated bash completion. The narrow check keys on
// the subcommand-offering form the generator emits (`commands+=("<name>")`),
// NOT a loose substring — the finalized completion candidate surface
// (session-name / alias-key candidates) is Phase 6 and out of scope here.
func TestRetiredSurface_AbsentFromCompletion(t *testing.T) {
	buf := new(bytes.Buffer)
	if err := rootCmd.GenBashCompletion(buf); err != nil {
		t.Fatalf("GenBashCompletion: %v", err)
	}
	out := buf.String()
	for _, verb := range retiredVerbs {
		offering := fmt.Sprintf("commands+=(%q)", verb)
		if strings.Contains(out, offering) {
			t.Errorf("bash completion offers retired verb as a subcommand (%s)", offering)
		}
	}
}

// TestRetiredSurface_AbsorbedBehavioursReachableViaOpen asserts every former
// attach/spawn behaviour survives on `open`: the exact/no-guess attach pin
// (--session, Phase 2), the spawned-window receipt flag (--ack, hidden, Phase
// 3), and multi-target positionals (the multi-window burst).
func TestRetiredSurface_AbsorbedBehavioursReachableViaOpen(t *testing.T) {
	// (1) exact/no-guess attach — former `attach` job, now `open --session`.
	if openCmd.Flags().Lookup("session") == nil {
		t.Error("open must expose --session (absorbs attach's exact/no-guess attach)")
	}

	// (2) spawned-window receipt — former `attach --spawn-ack`, now the hidden
	// `open --ack`. Present AND hidden (gone from --help / completion).
	ack := openCmd.Flags().Lookup("ack")
	if ack == nil {
		t.Fatal("open must expose --ack (spawned host-window receipt flag)")
	}
	if !ack.Hidden {
		t.Error("open --ack must be hidden (internal receipt flag, absent from --help/completion)")
	}

	// (3) multi-window burst — former `spawn <sessions…>`, now multi-target
	// `open <t1> <t2> …`. Assert the BEHAVIOUR (2 positionals admitted), not the
	// specific validator identity — a wrapper validator is fine so long as it
	// does not reject two positionals.
	if openCmd.Args != nil {
		if err := openCmd.Args(openCmd, []string{"a", "b"}); err != nil {
			t.Errorf("open must admit >=2 positional targets (multi-target burst); Args rejected 2 positionals: %v", err)
		}
	}
}

// TestOpenHelpMetadata_DescribesRedesignedVerb is a cheap guard against the
// top-level `open` help re-staling into the pre-redesign single-destination
// wording (Task 10-1). It asserts the Short/Long copy names the redesigned
// surface — session-name attach, the domain pins, -f/--filter, -e/-- command
// scoping, and multi-target opening — and no longer implies a single path
// "destination". It intentionally pins intent (keywords), not a golden string,
// so accurate copy edits don't churn the test.
func TestOpenHelpMetadata_DescribesRedesignedVerb(t *testing.T) {
	// Use must reflect the target-set shape, not a single [destination].
	if strings.Contains(openCmd.Use, "destination") {
		t.Errorf("openCmd.Use still implies a single [destination]: %q", openCmd.Use)
	}

	// Short must name what the verb does now (multiple targets and/or picker) and
	// must not carry the stale "start a session at a path" single-destination copy.
	short := strings.ToLower(openCmd.Short)
	if strings.Contains(short, "at a path") {
		t.Errorf("openCmd.Short still reads like the single-path pre-redesign command: %q", openCmd.Short)
	}
	if !strings.Contains(short, "target") && !strings.Contains(short, "portal") {
		t.Errorf("openCmd.Short does not name the multi-target surface: %q", openCmd.Short)
	}
	if !strings.Contains(short, "picker") {
		t.Errorf("openCmd.Short does not mention the interactive picker: %q", openCmd.Short)
	}

	// Long must describe the full redesigned surface: session-name attach, each of
	// the four domain pins, -f/--filter, -e/-- command scoping, and multi-target.
	if openCmd.Long == "" {
		t.Fatal("openCmd.Long is empty; expected a description of the redesigned surface")
	}
	long := strings.ToLower(openCmd.Long)
	for _, want := range []string{
		"picker",     // no-args → interactive picker
		"session",    // session-name attach
		"attach",     // attach outcome named
		"mint",       // mint outcome named
		"-s",         // --session pin
		"-p",         // --path pin
		"-a",         // --alias pin
		"-z",         // --zoxide pin
		"-f",         // --filter
		"-e",         // --exec command scoping
		"--",         // command separator
		"precedence", // the resolution precedence chain
	} {
		if !strings.Contains(long, want) {
			t.Errorf("openCmd.Long omits %q; full surface not described:\n%s", want, openCmd.Long)
		}
	}
	// Multi-target opening must be described (host-terminal windows / N surfaces).
	if !strings.Contains(long, "window") && !strings.Contains(long, "surface") {
		t.Errorf("openCmd.Long does not describe multi-target opening:\n%s", openCmd.Long)
	}
}
