# Minimal demo shell: a clean prompt and the `x` alias most people bind to the
# portal picker. The presence of this file also suppresses zsh's first-run
# new-user wizard.
export TERM=xterm-256color
autoload -Uz colors && colors
PROMPT='%F{45}%1~%f %F{246}❯%f '
RPROMPT=''
alias x='portal open'
